title: "Training"
baseurl: "/training"  # â† required for GitHub project pages

markdown: kramdown

collections:
  training:
    output: true
    permalink: /training/:name/

defaults:
  - scope:
      path: ""
      type: training
    values:
      layout: default
